//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebApp.ClienteServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/CampanhaService")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> telCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal telResidencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                if ((this.dataNascimentoField.Equals(value) != true)) {
                    this.dataNascimentoField = value;
                    this.RaisePropertyChanged("dataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> telCelular {
            get {
                return this.telCelularField;
            }
            set {
                if ((this.telCelularField.Equals(value) != true)) {
                    this.telCelularField = value;
                    this.RaisePropertyChanged("telCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal telResidencial {
            get {
                return this.telResidencialField;
            }
            set {
                if ((this.telResidencialField.Equals(value) != true)) {
                    this.telResidencialField = value;
                    this.RaisePropertyChanged("telResidencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteServiceReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteById", ReplyAction="http://tempuri.org/IClienteService/GetClienteByIdResponse")]
        ClienteWebApp.ClienteServiceReference.Cliente GetClienteById(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteById", ReplyAction="http://tempuri.org/IClienteService/GetClienteByIdResponse")]
        System.Threading.Tasks.Task<ClienteWebApp.ClienteServiceReference.Cliente> GetClienteByIdAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteByNome", ReplyAction="http://tempuri.org/IClienteService/GetClienteByNomeResponse")]
        ClienteWebApp.ClienteServiceReference.Cliente[] GetClienteByNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteByNome", ReplyAction="http://tempuri.org/IClienteService/GetClienteByNomeResponse")]
        System.Threading.Tasks.Task<ClienteWebApp.ClienteServiceReference.Cliente[]> GetClienteByNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/UpdateCliente", ReplyAction="http://tempuri.org/IClienteService/UpdateClienteResponse")]
        void UpdateCliente(ClienteWebApp.ClienteServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/UpdateCliente", ReplyAction="http://tempuri.org/IClienteService/UpdateClienteResponse")]
        System.Threading.Tasks.Task UpdateClienteAsync(ClienteWebApp.ClienteServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteCampanha", ReplyAction="http://tempuri.org/IClienteService/GetClienteCampanhaResponse")]
        ClienteWebApp.ClienteServiceReference.Cliente[] GetClienteCampanha();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteCampanha", ReplyAction="http://tempuri.org/IClienteService/GetClienteCampanhaResponse")]
        System.Threading.Tasks.Task<ClienteWebApp.ClienteServiceReference.Cliente[]> GetClienteCampanhaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : ClienteWebApp.ClienteServiceReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<ClienteWebApp.ClienteServiceReference.IClienteService>, ClienteWebApp.ClienteServiceReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebApp.ClienteServiceReference.Cliente GetClienteById(long id) {
            return base.Channel.GetClienteById(id);
        }
        
        public System.Threading.Tasks.Task<ClienteWebApp.ClienteServiceReference.Cliente> GetClienteByIdAsync(long id) {
            return base.Channel.GetClienteByIdAsync(id);
        }
        
        public ClienteWebApp.ClienteServiceReference.Cliente[] GetClienteByNome(string nome) {
            return base.Channel.GetClienteByNome(nome);
        }
        
        public System.Threading.Tasks.Task<ClienteWebApp.ClienteServiceReference.Cliente[]> GetClienteByNomeAsync(string nome) {
            return base.Channel.GetClienteByNomeAsync(nome);
        }
        
        public void UpdateCliente(ClienteWebApp.ClienteServiceReference.Cliente cliente) {
            base.Channel.UpdateCliente(cliente);
        }
        
        public System.Threading.Tasks.Task UpdateClienteAsync(ClienteWebApp.ClienteServiceReference.Cliente cliente) {
            return base.Channel.UpdateClienteAsync(cliente);
        }
        
        public ClienteWebApp.ClienteServiceReference.Cliente[] GetClienteCampanha() {
            return base.Channel.GetClienteCampanha();
        }
        
        public System.Threading.Tasks.Task<ClienteWebApp.ClienteServiceReference.Cliente[]> GetClienteCampanhaAsync() {
            return base.Channel.GetClienteCampanhaAsync();
        }
    }
}
